[build-system]
requires = [
    "setuptools >= 46.4.0",
    "wheel",
    "setuptools_scm[toml] >= 6.3.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "example_package_for_flf/_version.py"
