name: my_CI

on:
  push:


jobs:
  testing:

      steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install package
        run: |
          pip install --upgrade pip
          pip install .